services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8000:8000"
    networks:
      - devsecops

  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app
    networks:
      - devsecops

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - devsecops

networks:
  devsecops:
    driver: bridge
